CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Login NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(50) NOT NULL,
    Avatar VARBINARY(MAX) NOT NULL,
	ColorBrush NVARCHAR(10) NOT NULL,
    ChatId INT NULL -- ID чата, если пользователь состоит в одном основном чате
);

CREATE TABLE Chats (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NULL, -- NULL для личных чатов
    IsGroup BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE ChatUsers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ChatId INT NOT NULL,
    UserId INT NOT NULL,
    FOREIGN KEY (ChatId) REFERENCES Chats(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Messages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ChatId INT NOT NULL,
    UserId INT NOT NULL,
    Content VARBINARY(MAX) NOT NULL,
    Timestamp DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ChatId) REFERENCES Chats(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Files (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MessageId INT NOT NULL,
    BFile VARBINARY(MAX) NOT NULL,
    FOREIGN KEY (MessageId) REFERENCES Messages(Id) ON DELETE CASCADE
);

CREATE TABLE Stickers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Image VARBINARY(MAX) NOT NULL
);

CREATE TABLE GIFs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    BFile VARBINARY(MAX) NOT NULL
);